# Generated by Django 5.2.8 on 2025-12-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_encrypted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_hmac',
        ),
    ]
