# Generated by Django 6.0.1 on 2026-01-21 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('action_link', models.CharField(help_text='Ссылка для действия, например: "begab://club/123"', max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число — тем выше приоритет')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0, help_text='Средний рейтинг клуба (кешированный)')),
            ],
        ),
    ]
