# Generated by Django 5.2.9 on 2025-12-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tg', '0002_remove_otp_email_alter_otp_code_alter_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
