# Generated by Django 5.2.8 on 2025-12-01 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sanoat Rivoji', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='Yangi', max_length=200, verbose_name='Подзаголовок')),
                ('content', models.TextField(help_text='Основной текст статьи', verbose_name='Содержимое')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='Год')),
                ('statistic', models.CharField(blank=True, default='+12% o‘sish', max_length=100, verbose_name='Статистика (текст)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='industry_images/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статья о промышленности',
                'verbose_name_plural': 'Статьи о промышленности',
                'ordering': ['-created_at'],
            },
        ),
    ]
