# Generated by Django 5.2.8 on 2025-12-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('base_title', models.CharField(max_length=255)),
                ('title', models.CharField(editable=False, max_length=255)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
